PLATFORM_PATH = win32
PLATFORM_NAME = Win32
TIME_PLATFORM_PATH = win32
TIME_PLATFORM_NAME = Win32

# Ajout de l'option -DWIN32
PLATFORM_COMPILE_FLAGS = -I../SDL/include -DWIN32

# -mwindows hides the command window on app launch
PLATFORM_LINK_FLAGS = -lmingw32 -lSDLmain -lSDL -mwindows


